#!/usr/bin/env python3
"""
Pre-build script for compressing web assets (CSS, JS) into gzipped binary arrays.
This script runs before each build and generates src/web_assets.h
"""

import os
import gzip
import hashlib

# Check if running within PlatformIO build environment
try:
    Import("env")
    PROJECT_DIR = env["PROJECT_DIR"]
    print("[PlatformIO] Running asset compression script...")
except (NameError, KeyError):
    # Standalone mode
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    print("[Standalone] Running asset compression script...")

WEB_DIR = os.path.join(PROJECT_DIR, "web")
OUTPUT_FILE = os.path.join(PROJECT_DIR, "src", "web_assets.h")

# Files to compress
ASSETS = {
    "styles_css": os.path.join(WEB_DIR, "styles.css"),
    "scripts_js": os.path.join(WEB_DIR, "scripts.js"),
    "map_editor_css": os.path.join(WEB_DIR, "map_editor.css"),
    "map_editor_js": os.path.join(WEB_DIR, "map_editor.js"),
    "bg_color_editor_css": os.path.join(WEB_DIR, "bg_color_editor.css"),
    "bg_color_editor_js": os.path.join(WEB_DIR, "bg_color_editor.js"),
    "ui_schema_models_json": os.path.join(WEB_DIR, "ui_schema_models.json"),
    "ui_schema_sections_json": os.path.join(WEB_DIR, "ui_schema_sections.json"),
    "ui_schema_controls_json": os.path.join(WEB_DIR, "controls.json"),
}


def compress_file(file_path):
    """Read file and compress with gzip (level 9)"""
    with open(file_path, "rb") as f:
        data = f.read()

    # Compress with maximum compression (mtime=0 for deterministic output)
    compressed = gzip.compress(data, compresslevel=9, mtime=0)

    # Calculate hash for versioning/ETag
    file_hash = hashlib.sha256(compressed).hexdigest()[:16]

    return compressed, file_hash, len(data), len(compressed)


def bytes_to_c_array(data, var_name):
    """Convert binary data to C++ array format"""
    # Format: const uint8_t array_name[] = { 0x00, 0x01, ... };
    hex_values = ", ".join(f"0x{b:02x}" for b in data)

    # Split into multiple lines for readability (16 bytes per line)
    lines = []
    bytes_list = [f"0x{b:02x}" for b in data]
    for i in range(0, len(bytes_list), 16):
        chunk = bytes_list[i : i + 16]
        lines.append("    " + ", ".join(chunk))

    formatted = ",\n".join(lines)

    return f"const uint8_t {var_name}[] PROGMEM = {{\n{formatted}\n}};"


def generate_header():
    """Generate C++ header file with compressed assets"""
    print("=" * 60)
    print("Compressing web assets...")
    print("=" * 60)

    header_content = """// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by tools/compress_assets.py
// Contains gzip-compressed web assets

#ifndef JAAM_WEB_ASSETS_H
#define JAAM_WEB_ASSETS_H

#include <Arduino.h>

"""

    stats = []

    for asset_name, file_path in ASSETS.items():
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Asset file not found: {file_path}")

        compressed, file_hash, original_size, compressed_size = compress_file(file_path)
        ratio = (1 - compressed_size / original_size) * 100 if original_size > 0 else 0

        # Print compression stats
        print(f"\n📦 {os.path.basename(file_path)}")
        print(f"   Original:   {original_size:6d} bytes")
        print(f"   Compressed: {compressed_size:6d} bytes")
        print(f"   Ratio:      {ratio:5.1f}% reduction")
        print(f"   Hash:       {file_hash}")

        stats.append(
            {
                "name": os.path.basename(file_path),
                "original": original_size,
                "compressed": compressed_size,
                "ratio": ratio,
            }
        )

        # Generate C++ array
        array_c = bytes_to_c_array(compressed, f"{asset_name}_gz")

        # Add to header
        header_content += (
            f"// {os.path.basename(file_path)} - {original_size} → {compressed_size} bytes ({ratio:.1f}% reduction)\n"
        )
        header_content += array_c + "\n"
        header_content += f"const size_t {asset_name}_gz_len = {compressed_size};\n"
        header_content += f'const char {asset_name}_hash[] = "{file_hash}";\n\n'

    header_content += "#endif // JAAM_WEB_ASSETS_H\n"

    # Write header file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(header_content)

    print("\n" + "=" * 60)
    print(f"✅ Generated: {OUTPUT_FILE}")

    total_original = sum(s["original"] for s in stats)
    total_compressed = sum(s["compressed"] for s in stats)
    total_ratio = (1 - total_compressed / total_original) * 100 if total_original > 0 else 0

    print("\n📊 Total compression:")
    print(f"   Original:   {total_original:6d} bytes")
    print(f"   Compressed: {total_compressed:6d} bytes")
    print(f"   Saved:      {total_original - total_compressed:6d} bytes ({total_ratio:.1f}%)")
    print("=" * 60)


# Run on build
generate_header()
